mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^authenticate/$', views.authenticate, name='authenticate'),
    url(r'^(?P<slug>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<slug>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.template.defaultfilters import slugify


#The Class which keeps a record of student records
class Students(models.Model):
    student_id = models.IntegerField(primary_key=True)
    grade = models.IntegerField() #this will be deleted after PAM
    password = models.CharField(max_length=30, blank=True, null=True) #this will be deleted after PAM
    #This will be a huge-ass string used solely for authentication/record purposes: it will just be a concatenated list of all of the student's votes
    votes = models.TextField(blank = True, null = True)
    class Meta:
        verbose_name_plural = "Students"

class Category(models.Model):
    category_text = models.CharField(max_length = 200)
    category_num = models.IntegerField(default = 0)
    pub_date = models.DateTimeField('date published')
    grade_level = models.IntegerField(default = 0)

    #I used slugs as an alternative for primary keys because:
    #1) primary keys can get nasty and become anachronistic when data is edited
    #2) it's easier to keep track of slugs
    slug = models.CharField(max_length=200)
    def save(self, *args, **kwargs):
        self.slug = slugify(self.category_num)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = "Categories"

class Candidate(models.Model):
    category = models.ForeignKey(Category)
    candidate_name = models.CharField(max_length = 200)
    image = models.ImageField(upload_to='candidate_pics', blank=True, null=True)
    motto = models.CharField(max_length=500, blank = True, null = True)
    votes = models.IntegerField(default = 0)

polls/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Students

class LoginForm(forms.Form):
        username = forms.CharField(label='Username',max_length = 6)
        password = forms.CharField(label='Enter your BINX/ School Password',max_length=10, widget=forms.PasswordInput)
        def clean(self):
                if not str(self.cleaned_data.get('username')).isdigit():
                        raise ValidationError("Invalid Username")
                        return self.cleaned_data
        
                entries  = Students.objects.filter(student_id=self.cleaned_data.get('username'))
                if not entries:
                        raise ValidationError("Incorrect Username")
                        return self.cleaned_data
        
                if entries and entries[0].password != self.cleaned_data.get('password'):
                        raise ValidationError("Incorrect Password")
        
                return self.cleaned_data

polls/views.py
import random

from django.contrib.auth import authenticate, login, logout
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django import forms

from .forms import LoginForm
from .models import Candidate, Category, Students


#Render the Home Page
def index(request):
    categories = Category.objects.order_by("-category_num")
    context = {'category_list': categories}
    return render(request, 'polls/index.html',context)

#Authenticate the login
#Step 1: Authenticate with PAM backend
#Step 2: Ensure that the user has not voted
#Step 3: Access Grade Level via ....
#Step 4: Create session variables for user_grade, student_id, and votes array
def authenticate(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            #username = form.cleaned_data.get('username')
            #password = form.cleaned_data.get('password')
            #user = authenticate(username=username, password=password)
            #if user is not None:
                #entries  = Students.objects.filter(student_id=username)
                #if entries:
                    #return HttpResponseRedirect(reverse('polls:already_voted'))
                    #request.session['student_id'] = username
                #user_grade???
            entries  = Students.objects.filter(student_id=form.cleaned_data.get('username'))
            request.session['user_grade'] = entries[0].grade
            request.session['votes'] = []
            return HttpResponseRedirect(reverse('polls:detail',args=(1,))) #Go to the first voting page
    else:
        form = LoginForm()

    return render(request, 'polls/login.html',{'form':form})

#The View for the Voting Pages - this will display candidates along with their mottos in a pseudo-random order
@login_required
def detail(request, category_id):
    category = get_object_or_404(Category, slug=slug)
    #A grade_level of 0 indicates that it applies to all grades
    if category.grade_level == request.session['user_grade'] or category.grade_level == 0:
        #Randomizing
        candidate_list = category.candidate_set.all()
        candidates = []
        #exclude "abstain" option from randomization - want it to be last
        for x in range(0,len(candidate_list)-1):
            candidates.append(candidate_list[x])
        random.shuffle(candidates)
        candidates.append(candidate_list[len(candidate_list)-1])
        #Render up the detail page with the randomized list
        return render(request, 'polls/detail.html', {'candidates': candidates,'category':category})
    elif category.category_num + 1 >= Category.objects.count():
        return HttpResponseRedirect(reverse('polls:thanks'))
    else:
        return HttpResponseRedirect(reverse('polls:detail',args=(category.category_num+1,)))

@login_required
def vote(request, slug):
    p = get_object_or_404(Category, slug=slug)
    try:
        selected_candidate = p.candidate_set.get(pk=request.POST['candidate'])
    except (KeyError, Candidate.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'category': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        votes = request.session['votes']
        votes.append(selected_candidate.candidate_name)
        request.session['votes'] = votes
        selected_candidate.votes += 1
        selected_candidate.save()
    if p.category_num >= Category.objects.count():
            return HttpResponseRedirect(reverse('polls:thanks'))
    else:
        return HttpResponseRedirect(reverse('polls:detail',args=(p.category_num+1,)))

@login_required
def thanks(request):
    #student = Student()
    #student.username = request.session['student_id']
    #votes_str = ' '.join(request.session['votes'])
    #student.votes = votes_str
    #student.save()
    #logout(request)
    return render(request, 'polls/thanks.html')

def already_voted(request):
	return render(request, 'polls/already_voted.html')

polls/templates/polls/already_voted.html
<h1>Son, you've already voted</h1>

polls/templates/polls/detail.html
<h1>{{ category.category_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' category.slug %}" method="post">
{% csrf_token %}
{% for candidate in candidates %}
    <input type="radio" name="candidate" id="candidate{{ forloop.counter }}" value="{{ candidate.id }}" />
    <label for="candidate{{ forloop.counter }}">{{ candidate.candidate_name }}</label><br />
{% endfor %}
<br />
<br />
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name = "author" content = "Eshan Tewari">

<title>The 2016 SGA Election</title>
<!-- styling -->
<!-- http://colorschemedesigner.com/#2q21Tw0w0w0w0 -->
<link href="http://fonts.googleapis.com/css?family=Overlock|Lily+Script+One|Oxygen|Questrial" rel="stylesheet" type="text/css">


<link rel="stylesheet" href="{% static 'polls/css/styles.css' %}">
</head>
<body>

<div id = "header">
<div id="logos">
<h1><center><span>Welcome</span> </center> </h1>
<h1><center>to the 2016 Spring SGA Election Portal</center></h1>
</div>
</div>

<div id="content">
<div id = "instructions">
<p> Welcome young scholars!  Enter your login info and click the button below to exercise the voting the glorious concept of democracy grants you! </p>
<p>This site will guide you through the process of voting for candidate(s) in the 2014 SGA election. Your votes are anonymous.</p>

<p><strong>Please do not use the back buttons in the browser or try to exit out of the voting process until you see the confirmation page.</strong> However, if you must go back/exit out for some reason, please request assistance.</p>
</div>
<div id = "input">
{% if category_list %}

<form action="{% url 'polls:authenticate' %}">
<div id = "button">
<button type="submit" name="" value="" class="css3button">Come on man, Let's Go! No brainwashing here...
</div>
</form>
</div>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</div>
</body>
</html>

polls/templates/polls/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name = "author" content = "Eshan Tewari">

<title>The 2016 SGA Election</title>
<!-- styling -->
<!-- http://colorschemedesigner.com/#2q21Tw0w0w0w0 -->
<link href="http://fonts.googleapis.com/css?family=Overlock|Lily+Script+One|Oxygen|Questrial" rel="stylesheet" type="text/css">


<link rel="stylesheet" href="{% static 'polls/css/styles.css' %}">
</head>
<body>
<p>Please Use Your School Username and Password.  And don't test the system.  I will find you. </p>
<div id="input">
<form action="{% url 'polls:authenticate' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>
</div>
</body>
</html>

polls/templates/polls/results.html
<h1>{{ category.category_text }}</h1>

<ul>
{% for candidate in category.candidate_set.all %}
    <li>{{ candidate.candidate_name }} -- {{ candidate.votes }} vote{{ candidate.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' category.category_num %}">Vote again?</a>

polls/templates/polls/thanks.html
<h1>Thank You!</h1>